services:
  postgres:
    image: postgis/postgis  # Use the PostGIS image if you need spatial functionalities
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: myuser
    ports:
      - '5432:5432'  # Map container port 5432 to host port 5432
    labels:
      org.springframework.boot.service-connection: postgres  # Spring Boot service discovery label
